### ISSUE TITLE
Converter profile for Material_Materials_All

### ISSUE THREAD

**Issue by mark-cooper** [collectionspace/cspace-converter#133]
Mapping

https://github.com/collectionspace/cspace-converter/blob/master/lib/collectionspace/converter/materials/material.rb

Data

https://github.com/collectionspace/cspace-converter/blob/master/data/materials/material_materials_all.csv

@meganforbes need data.

Config: use "materials"

https://github.com/lyrasis/cspace-converter/blob/master/DEV.md#materials
https://materials.dev.collectionspace.org

Start by manually creating a record in cspace using first row of sample data, using only the identifier and any new / updated fields. Export the XML then delete the record from cspace. Upload copy of XML here. From the converter you can use: bundle exec rake remote:get[$type/$csid] to get the XML.

Implement fields not covered in mapping currently.
Fields already mapped in Core do not need to be mapped again.
If a field was not mapped in core but belongs in core it should be added there.
If a field mapping needs to be changed add the field name to the redefined_fields list then map as normal.

**Comment by Paulmulonzia** [comment]
Hi @mark-cooper, 

Kindly advice on how to fetch the xml from cspace. 

I have tried the following which all return null:

bundle exec rake remote:get[materials/cb89532d-4d8b-4a0a-91eb]

bundle exec rake remote:get[material/cb89532d-4d8b-4a0a-91eb]

bundle exec rake remote:get[material/local/cb89532d-4d8b-4a0a-91eb]

bundle exec rake remote:get[materials/local/cb89532d-4d8b-4a0a-91eb]

**Comment by mark-cooper** [comment]
@Paulmulonzia try these out:

```
./bin/rake remote:get[materialauthorities]
./bin/rake remote:get["materialauthorities/urn:cspace:name(material)/items"]
```

**Comment by Paulmulonzia** [comment]
Hi @mark-cooper,

Kindly assist on how to implement a group list inside another group list as in the materials authority structure:

https://github.com/collectionspace/cspace-converter/blob/DDD-Materials-Authority_16-12-2019/spec/fixtures/files/materials_authority.xml#L96

My current implementation is **typicalSizeDimension** as a subgroup, which as expected fails to transfer to cspace since there is a mismatch in the structure:

https://github.com/collectionspace/cspace-converter/blob/DDD-Materials-Authority_16-12-2019/lib/collectionspace/converter/materials/material.rb#L184

I have pushed the current mapping which covers all fields with the exception of the dimensions fields due to the above issue, some of the challenges encountered:

**materialTermAttributionContributingNote** not available in cspace, so I had to drop it from the mapping for import to work.

**recycledContentQualifier** values provided in sample data are not valid list items in cspace.

**termPrefForLang** I had to change field values to use true/false rather than yes/no

**discontinuedDate** fields with null values failed import, so I had to use rescue nil.

Thanks.

**Comment by mark-cooper** [comment]
@Paulmulonzia I updated and merged your branch. There are a few issues remaining:

Discontinued and production date were not working so I commented them out for now. I want to remove all `rescue nil` and `if attributes[$]` type error handling from the mappings so if you find yourself wanting to do that then let me know so I can look into a better way of doing it.

The `typicalSizeDimension` stuff, as you mentioned. I don't have time time to dig into it right now, but perhaps some of the changes @kspurgin made are relevant? I believe you're at least partially in the loop on those changes and they were merged into master yesterday so your new branches will have access to the work Kristina has done.

**Comment by meganforbes** [comment]
@Paulmulonzia can you update on current status?

**Comment by Paulmulonzia** [comment]
Hi @meganforbes pushing an update shortly to fix discontinued/production date and dimensions fields.

Thanks.

**Comment by Paulmulonzia** [comment]
Hi @kspurgin @mark-cooper , I am having issues with transfer jobs to cspace. 
I am encountering the following error:

**Error during transfer: undefined method `body' for #<CollectionSpace::Response:0x0000563958406b58>**

But when I update an existing record, the operation is successful.

This error comes up despite having implemented the [authority identifier ](https://github.com/collectionspace/cspace-converter/blob/DDD-Materials-Authority_23-03-2019/lib/collectionspace/converter/materials/material.rb#L55) and the converter passing all spec tests.

Thanks.

**Comment by mark-cooper** [comment]
@Paulmulonzia sorry for the delay! Will take a look next week.
