### ISSUE TITLE
Converter profile for Cataloging_Core_All

### ISSUE THREAD

**Issue by mark-cooper** [collectionspace/cspace-converter#98]
Mapping

https://github.com/lyrasis/cspace-converter/blob/master/lib/collectionspace/converter/core/collectionobject.rb

Data

https://github.com/lyrasis/cspace-converter/blob/master/data/core/cataloging_core_excerpt.csv

Config: use "core"

https://github.com/lyrasis/cspace-converter/blob/master/DEV.md#core

Start by manually creating a record in cspace using first row of sample data. Export the XML then delete the record from cspace. Upload copy of XML here. From the converter you can use: bundle exec rake remote:get[groups/$csid] to get the XML.

Implement fields not covered in mapping currently.

**Comment by Paulmulonzia** [comment]
Hello @mark-cooper,

I updated a few fields on the converter. The following are some of the issues encountered:

**recordStatus** values in the sample data need to be lower case for import to work

The converter is using the add_measured_part_group_list helper which won't pick the **measuredPart** and **measurementUnit** fields since they appear as **dimensionPart** and **unit** respectively in the csv. 

The field **unit** has values that appear as in/cm rather than inches/centimeters in the sample data

I also had to recreate **objectProductionPeople** to not use the helpers for creating the group list as it was being created with the following structure:

<objectProductionPeopleGroupList>
      <objectProductionPeopleGroup>
        <objectProductionPerson>Tolowa</objectProductionPerson>
      </objectProductionPeopleGroup>
    </objectProductionPeopleGroupList>

rather than:

<objectProductionPeopleGroupList>
      <objectProductionPeopleGroup>
        <objectProductionPeople>Tolowa</objectProductionPeople>
      </objectProductionPeopleGroup>
    </objectProductionPeopleGroupList

The field **collection** values should not contain space in between and should be lower case e.g. Permanent Collection to permanent-collection

**responsibleDepartment** values should not have space in between e.g. Prints and Drawings should be prints-drawings

Thanks.

**Comment by Paulmulonzia** [comment]
I have updated the sample data to conform to the reference xml file and pushed the updated sample data file.

**Comment by mark-cooper** [comment]
@Paulmulonzia thx, much appreciated! There's still a little bit of work to do. All fields (in the first data row of the csv) should have sample data and the reference XML should be fully populated with data (from cspace) with the specs to match. When that's done I think this will be ready for QA with Megan.

**Comment by Paulmulonzia** [comment]
Hi @mark-cooper, I have updated a few of the empty fields with data.

I am however not sure the values to use on the following fields as they are blank not only for the first row but for the rest of the records:

 copyNumber, editionNumber, form, inscriber, method, objectStatus, phase, sex, style, techAttribute, objectComponentName.

Thanks.

**Comment by mark-cooper** [comment]
@meganforbes do you want to provide data for these fields?

**Comment by meganforbes** [comment]
Updated csv with all fields filled in row 1. LMK if you also need to to re-do the term lists so that it's the backend vs. the front end terms.

[sample_data_cataloging_core_excerpt.xlsx](https://github.com/collectionspace/cspace-converter/files/3847590/sample_data_cataloging_core_excerpt.xlsx)

**Comment by Paulmulonzia** [comment]
Thanks @meganforbes.

I will redo the term lists.

For the fields "Inscriber" and "method", do we put them under Textual or Non textual Inscription in cspace?

**Comment by mark-cooper** [comment]
I updated the core cat csv and modified the tests to match. Updates:

1. headers use camel case form (objectNumber), not standard English (consistent with all other spreadsheets).
2. static list terms updated to the backend form (but only where it caused tests to fail)
3. Updated reference XML to use new data

**Comment by Paulmulonzia** [comment]
Thank you @mark-cooper for the update

**Comment by kspurgin** [comment]
@Paulmulonzia In regard to the new fields for core collectionobject converter module Megan mentioned [here](https://github.com/collectionspace/cspace-converter/issues/113#issuecomment-564707787), a couple of further things: 

I'd sent Megan a field list of fields needed for this migration, but it changed after I sent it to her, so I double checked the sample data, converter tool code as of now, and the actual data we need to migrate. 

- Here's a new version of the sample data: [sample_data_cataloging_core_excerpt_V3.xlsx](https://github.com/collectionspace/cspace-converter/files/3952681/sample_data_cataloging_core_excerpt_V3.xlsx). It has a couple columns added, and, importantly, adds some multi-valued data in some fields. (The multivalued fields are separated with ';' and I added them values in the first couple of rows)

The data we are migrating has multi-valued data in the following fields already supported by the converter tool: 

- otherNumberList/otherNumber/numberValue
- otherNumberList/otherNumber/numberType
- inventoryStatusList/inventoryStatus
- objectNameList/objectNameGroup/objectName
- objectProductionPeopleGroupList/objectProductionPeopleGroup/objectProductionPeople

We need to make sure the converter tool can handle those multivalued fields. 

The fields/columns added to the sample data that are not currently supported in the master branch of the converter tool are: 

- assocPeopleGroupList/assocPeopleGroup/assocPeople
- assocPeopleGroupList/assocPeopleGroup/assocPeopleType
- fieldCollectionNote
- fieldCollectionFeature
- objectProductionPeopleGroupList/objectProductionPeopleGroup/objectProductionPeopleRole
- objectProductionNote

**Comment by Paulmulonzia** [comment]
Hi @kspurgin.

The sample data attached is having different field names from what is currently mapped on the converter. For example **numberValue** and **numberType** are otherNumber and otherNumberType respectively on the sample data.

I updated the field names to match the converter profile. Apart from that, the rest of the fields were succesfully transferred to cspace.

@mark-cooper I have pushed a new Cataloging branch with the new changes.

Thanks.

**Comment by Paulmulonzia** [comment]
The field values for **techAttribute** also had to be modified to use hyphen as a delimiter rather than using whitespace in between two words for the import to work.

**Comment by mark-cooper** [comment]
@Paulmulonzia I updated your branch. I had to uncomment some lines in the `core/collectionobject_spec.rb`, it looks like those fields need to be added to the sample data.

**Comment by mark-cooper** [comment]
@Paulmulonzia actually I'll merge that branch. So you can create a new branch off latest master to update the sample data / fix the spec. If you want to re-use a branch name that's completely fine by me but append the date to the branch name (like: `DDD-Core-Cataloging_12-12-2019`) so it's less confusing for me when encountering the same branch name again or slightly different :smile:

**Comment by Paulmulonzia** [comment]
Hi @mark-cooper.

I have pushed the updated sample data and spec file.

Apologies for the confusion in branch names, I will adopt different naming conventions going forward.

Thanks.

**Comment by mark-cooper** [comment]
:star:

**Comment by meganforbes** [comment]
Unable to QA this, getting the error message "Import error: ERROR: missing headers: objectnumber" with sample data pulled from https://github.com/collectionspace/cspace-converter/blob/master/data/core/cataloging_core_excerpt.csv. 

@mark-cooper

**Comment by meganforbes** [comment]
@mark-cooper Still an issue - can't import the data from the sample data. XLS version of just the first few lines in the sample data attached. 

[Sample Cataloging.xlsx](https://github.com/collectionspace/cspace-converter/files/4483153/Sample.Cataloging.xlsx)
